### ISSUE TITLE
「瓊」港版思源黑映射錯誤  用的是大陸日本標準的訛字  沒有按照港台及傳統標準望修正映射 感謝

### ISSUE THREAD

**Issue by jisbig5** [chiron-fonts/chiron-sans-hk#10]
昭源黑體已經成為網葉預設字型感謝製作

**Comment by tamcy** [comment]
謝謝告知本字體其實有人用(笑)。

已確認「瓊」字問題，屬思源黑體上游錯誤。我已提交 [issue report](https://github.com/adobe-fonts/source-han-sans/issues/288)，假如他們未及更新我也會在昭源黑體先行修正。

**Comment by jisbig5** [comment]
思源黑派生眾多 昭源黑是我唯一使用的 字重豐富 並且還有otf版  並重新繪製了部分字形改正了港版思源黑的不足 有沒有考慮將「瘟」「及」部件改為台版傳承字形?   再次感謝作者

**Comment by jisbig5** [comment]
思源黑派生眾多 昭源黑是我唯一使用的 字重豐富 並且還有otf版 並重新繪製了部分字形改正了港版思源黑的不足 有沒有考慮將「瘟」「及」部件改為台版傳承字形? (雖然港版標準是這樣的) 再次感謝作者

**Comment by jisbig5** [comment]
因為台灣輸入法 默認標準是「溫」這樣與「瘟」就不統一了 畢竟繁中實際情況用「溫」比「温」多 能否將「瘟」改為台版傳統寫法 這只是一個建議 一點也不影響我對昭源黑的喜愛

**Comment by jisbig5** [comment]
還有 能否將 「告」與「吿」互換編碼 或者統一為「吿」

**Comment by tamcy** [comment]
閣下提出的「瘟」、「告」根本原因在於 Unicode 編碼的來源分離原則。我雖然是香港人，但由於我是國喬倚天年代開始使用中文電腦，用倉頡輸入中文，習慣成自然，像「溫」「告」這類字，除非刻意為之，否則一般還是會輸入「溫」「告」而不是「温」和「吿」。而像「說説」這種在輸入法中以台灣寫法為首選的字更不用說了。事實上，香港的中文系統環境的確受台灣影響甚深，甚至在某程度上改變了香港的中文使用生態。

在這種情況，當兩地標準字形不同，製作字體時，必然要作出取捨。昭源黑體屬於一款 opinionated 的字體，而製作者（我）是香港人，無可否認當中的「港味」是比較濃，閣下提到的「瘟」只是眾多例子之一。由於上面提到的原因，這類字碼究竟應該選用何者，我會考慮我平日是怎麼去寫、在印刷體上是否看得順眼、本字體參考對象（蒙納黑體、華康儷黑）的取態等因素，但無論結果如何，肯定不能令所有人都滿意。這一點惟有希望使用者多多包涵。我明白閣下遇到的是單一編碼字形跟因字源分離而分開編碼的預設輸出字形不搭調的問題，我想指出的是，這問題其實也同樣發生在字體製作者（我）身上。

至於「告」字，在製作前期，我也有想過能不能將因為來源分離原則而分開編碼的字（說説、告吿之類）統一字形。後來打消念頭，是因為我想將昭源黑體定位成一款 general purpose 適合一般用途的字體。

舉例說，比如告字，香港字形標準說明是「或作告、今作吿」。假如我將兩個字碼的字形顛倒，套用了本字體後，整句話的意思就完全相反。而假如字體將兩個編碼都做成同一字形，整句話更是變得不知所云。我明白在個別場合（例如書刊印刷），統一不同編碼的字形會有其好處。但這種情況不一定要靠更改字體解決，這亦不符本字體適合一般用途的原則。

順帶一提，蒙納黑體正是將「說」做成「説」、「告」做成「吿」的例子。不過，蒙納黑體是一款只支援 Big5/HKSCS 字集的字體，在 HKSCS 仍是以 Big5 擴展為基礎、未過渡到 Unicode 之前，「說 (U+8AAA)、告 (U+544A)」只有一個碼位、沒有分開編碼，蒙納黑體也不支援「説 (U+8AAC)、吿 (U+543F)」兩個字碼，所以這款字體將「說 (U+8AAA)、告 (U+544A)」造成「説、吿」的模樣並無問題。但昭源黑體是一款 Unicode 覆蓋字體，本身已經覆蓋「說、説」和「告、吿」，所以不能這樣無視 Unicode 規格。而事實上蒙納在支援「說、説、告、吿」字碼的翔鶴黑體也將各字做回符合 Unicode 規格的面貌。

**Comment by tamcy** [comment]
Fixed in v2.034.
