### ISSUE TITLE
「骨、及」二字的Medium字型同其他不一致

### ISSUE THREAD

**Issue by karlvlam** [chiron-fonts/chiron-sans-hk#11]
多謝作者們整呢個字體 Orz

**Comment by tamcy** [comment]
「骨、及」二字跟思源港版完全相同，沒有修改過（下圖是 Medium 字重）。不知「不一致」是甚麼意思？

![9aa8](https://user-images.githubusercontent.com/959433/110235947-11ff3480-7f6e-11eb-87bc-483fdcc3364b.png)

**Comment by karlvlam** [comment]
sorry, 認該是我browser設定自定字型的問題。
