### ISSUE TITLE
我有一個開源字體項目 求大神代為發佈

### ISSUE THREAD

**Issue by jisbig5** [chiron-fonts/chiron-sans-hk#12]
這個項目是基於開源字體「香港民間字集」(https://github.com/hfhchan/hkcs)
我對其進行增補可替換的異體字(458字) 並對部分字形進行優化
製作平臺使用「字形維基」線上繪製
這個字體製作初衷是能盡可能顯示古字  所以收錄了擴展b區漢字
為了節省空間  不收簡體中文 幽靈漢字
重繪的漢字結構 參考ipamj明朝 思源明朝
因為語言匱乏 不認識英文 加之有時還需要翻牆，字體編輯技術差等等諸多原因
懇請大神代為發佈 如能完善該字體那是最好 感謝
最後作為繁體中文使用者感謝大神的為對開源字體的貢獻
下載地址: https://mega.nz/file/5gQjjIiT#PmLf8_8j8ZEpuDUbxsRsu7SPe3yMTFCa21XndUXzqPY

**Comment by tamcy** [comment]
抱歉，自顧不暇，無能力兼顧其他項目。建議你可以用自己的 Github 帳戶發表。
