### ISSUE TITLE
字重Normal與Regular差別? 是否可顯示在預覽網頁?

### ISSUE THREAD

**Issue by xjlin0** [chiron-fonts/chiron-sans-hk#13]
謝謝你們的努力, 字體非常棒!

當我看到字重裡面同時有Normal與Regular, 我很疑惑差別在哪裏? 如果因瀏覽器限制, 不能加在"昭源黑體線上預覽"裡面, 是否可以加文字說明, Normal字重介於誰與誰之間等等?

謝謝!

**Comment by tamcy** [comment]
茲引述思源黑體（昭源黑體上游版本）的解說如下：
![weights](https://user-images.githubusercontent.com/959433/110263034-6fd46080-7ff0-11eb-845b-e2f5a8e3e87f.png)

在本字體，Normal 比 Regular 略細，在小字號幾乎看不出分別。思源黑體是 Adobe 與 Google 的合作成果，根據官方說明，之所以有兩個如此接近的字重，是因為 [Regular 用來跟 Google 其他語系的開源字體產品線 (Noto Sans / Roboto) 搭配較佳](https://github.com/adobe-fonts/source-han-sans/issues/5#issuecomment-49159574)，而 Normal 相信跟 Adobe 的開源英文字體搭配視覺上較佳。對使用者而言，可以按需要或個人喜好選擇其中一個作為標準字重，也可以增加與英文字體配搭時的彈性。

至於預覽問題，是因為以前在 webfont 定義字重 (font-weight) 值必須為100 的倍數：
![weight](https://user-images.githubusercontent.com/959433/110263283-351ef800-7ff1-11eb-8584-b90374f175e9.png)
(來源: https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight)

由於 Light 已佔據字重 300，而 Normal/Regular 佔用字重 400，同一網頁不能同時載入 Normal，Regular（後載入者會覆蓋前者），這是網頁沒有提供 Normal 和 Regular 供預覽的原因。

不過，近年的瀏覽器開始支援 Variable Fonts，可以容許 font-weight 採用任何數值。我剛測試過，目前瀏覽器已經容許為字重定義 300-400 之間的值。所以，下次更新時會將 Normal 字重賦予新字重值，用家便可以在同一網頁同時使用 Normal / Regular （雖然這樣做意義不大）。

**Comment by tamcy** [comment]
Resolved in v2.034.
