### ISSUE TITLE
建議將「尘」的「小」與少 尖 等字統一換上帶鉤的

### ISSUE THREAD

**Issue by jisbig5** [chiron-fonts/chiron-sans-hk#14]
舊版「思源黑」收錄了兩種字形的尘  新版刪除了 建議把尘 替換成舊版的「尘」只是建議 並不算bug 改不改都可 畢竟「尘」屬於不常用的俗字

**Comment by tamcy** [comment]
謝謝建議，不過正如我在網頁指出：

>昭源黑體畢竟是我在工餘時間製作和維護的字體專案，在人力和時間上都不容許我將「香港字符集」中全部不符本字體製作方針的字形都改成個人屬意的樣式，遑論原字體中「香港版」支援範圍之外、不屬「香港字符集」的字碼。

基於 U+5C18 尘 並不屬於 Big5 / HKSCS 字符集內，而正如閣下所講此字並不常用，因此不會作出修改。
