### ISSUE TITLE
想在此感謝作者的努力 ！!

### ISSUE THREAD

**Issue by CircleCurve** [chiron-fonts/chiron-sans-hk#15]
因為工作原因需要Export PDF 的功能, 使用了Google font中的Noto fonts, 卻不幸發現OTF 版本與dompdf 有相衝， 不能開啟Font subsetting （do not have glyf table) , 而令到PDF 文檔**因文字匯入而非常龐大**， 幸好找到了**TTF 版的昭源黑體** ， 謝謝作者

[https://github.com/dompdf/dompdf/issues/141](https://github.com/dompdf/dompdf/issues/141)
[https://github.com/PhenX/php-font-lib/issues/65](https://github.com/PhenX/php-font-lib/issues/65)

**Comment by tamcy** [comment]
You are welcome. Glad to know it's useful to you!
