### ISSUE TITLE
獎美英 吳娛誤 等字  下面不統一  望修正

### ISSUE THREAD

**Issue by jisbig5** [chiron-fonts/chiron-sans-hk#16]
獎美英央 吳娛誤 等字  下面不統一  望修正 再次感謝tamcy

**Comment by tamcy** [comment]
- 「娛」會在下一版修改。
- 「美」目前會保留不動。留意媄、渼、羹等等下方都作捺筆，在這個部件而言是一致的

昭源黑體建基於香港字形標準，而這類字香港字形跟台灣字形均傾向作頓點。而中日韓標準字形將捺筆改成頓點的傾向較小，於是在製作昭源黑體而須修改字形時，就經常會遇到其他地區明明已經有適合昭源黑體的字形，偏偏只差一個「從捺或是從頓點」的差異。如果要強制達到此一部件的一致性，必須人手修改。這類字為數不少，所須人力和時間太大，所以最後選擇了折衷方案：在以香港標準字形為基礎下，放寬「整體規律性」，但仍盡量保持「部件一致性」，改與不改的主要考慮因素是（一）美觀性、（二）常用字在其他地區是否有足夠可用字形。像「美」字，選擇用捺筆是因為本身這個字的左右對稱性質，而思源有足夠可用字形，改用捺筆不必人手修改字圖。同類例子還有「菐」，僕撲噗等字均作捺。

當然，也得承認在昭源黑體中的「部件一致性」也不是絕對。字體中有好些同部件字從捺還是從點，也會因為對映到其他地區而出現不一致。這主要是在捺點差異不在字底、思源不會將點筆跟其他筆畫斷開的情況。例如，「禾」字在上的字（以整個部件如季、香為單位），我是首選從捺筆的字形。但當其他地區沒有適合字形、而從捺與否是字形唯一差異時，也未必會特意去改。

至於你提到的「英央」，香港參考字形標準本身就是如此。而台灣字形「突」字的犬末筆作捺，「葖」字則作點。所以我認為這不是甚麼統不統一的問題，又或者說，我本來就不追求這一方面的統一，因為我認為一般人在閱讀時根本不會在意這種事，除非例如同一部件的兩個字組成詞語連在一起看才可能會特別顯眼。

**Comment by tamcy** [comment]
Fixed in v2.035.
