### ISSUE TITLE
關於昭源甄黑體版本的詢問

### ISSUE THREAD

**Issue by jisbig5** [chiron-fonts/chiron-sans-hk#19]
個人覺得昭源甄黑體修改的部件一點都不比新版思源黑差 並且還花了很多精力修改維護 即使不更新刪掉也是可惜了
剛從互聯網博物館恢復了昭源甄黑體 兩個都為otf版
 請問哪個更好 兩者有甚麼區別嗎?
再次感謝tamcy
CYanHeiHK_v1.011.7z
CYanHeiHK_v1.011_adjusted_fontbbox.7z

**Comment by tamcy** [comment]
其實我是將昭源甄黑體的專案隱藏了，因為近來仍然發現有關於這套字體的介紹，而我認為沒理由介紹一個最後更新已是四年前、擺明已經過時的版本，所以試試把它隱藏看看如何。若你問我哪個好，我會說昭源甄黑體兩個版本都不夠好，無論在字重選擇、字圖質量、字數支援、網頁字型技術上都是昭源黑體優勝。

至於兩個版本的分別，“adjusted_fontbbox” 跟昭源黑體 TTF 版移除豎排版 U+2E3A、U+2E3B 和 U+3031、U+3032 四個字圖目的一樣，都是作為繞過[某些軟件選框過大](https://github.com/googlefonts/noto-cjk/issues/66)問題的臨時解決辦法，只是做法不同。昭源黑體 TTF 版直接移除太高的字圖去達到較小的 FontBBox 高度值，昭源甄黑體則是直接修改 FontBBox 值，字體理論上仍支援這些字碼。理論是如此，實際調用這些字碼時礙於 FontBBox 值不正確，還是會出現排版異常。
