### ISSUE TITLE
以文本形式提供有改动的字形列表

### ISSUE THREAD

**Issue by NightFurySL2001** [chiron-fonts/chiron-sans-hk#21]
希望您可以提供文本形式的改动字形列表，目前以pdf形式提供让后续开发需要提取有点困难。

**Comment by tamcy** [comment]
請看看以下檔案格式是否你想要的：
[upstream_differences.txt](https://github.com/chiron-fonts/chiron-sans-hk/files/6950186/upstream_differences.txt)

檔案以剛發表的 2.043 為基礎列出各字圖異動。由於有些情況須解決（主要是在 Pro 版那邊）所以暫未 commit 到 Git。

**Comment by NightFurySL2001** [comment]
好的，非常感谢您的资讯。

不知您是否介意他人使用昭源黑体进行后续开发吗？另，不知您可以提供PS文件和制作可变字体的步骤吗？先此致谢。

**Comment by tamcy** [comment]
不知你所說的後續開發是甚麼意思，如果是指做昭源黑體為基礎製作其他字型產品（就像我用思源黑體為基礎製作出昭源黑體），那麼昭源黑體和思源黑體一樣採用 SIL OFL 授權，我當然是不介意（就算介意也不能阻止他人這樣做）。

.ps 檔方面，我是一直希望能增加一個 source branch 去放 .ps 檔和其他原始檔案（feature, cmap 檔之類）及相關指令，但這須大幅修改目前的製作流程和相關程式，很多一直用得好好的指令要做修改和重新測試，所以一直沒有時間去做（坦白說個人動機也不大，就算做也只會在 PRO 版做，兩版編譯流程差異太大，實在無力兼顧）。單單釋出 .ps 檔作用不大，要提取字形用原來的 .otf 就可以了。加上我無法肯定昭源的 .ps 檔是不是可依賴的對象，目前我個人是建議不如以思源黑體為基礎再結合本字體，畢竟用思源有甚麼疑問可以到官方 Github 找協助，無論是速度和權威性應該都要比我這邊要優勝得多。

**Comment by NightFurySL2001** [comment]
好的，谢谢您的回复。目前计划将会用到部分昭源黑体的部分字符，因此想要询问确认。ps档只是想要比较源头的文件，可能改用vf提取笔画分离版本。关于制作可变字体的步骤是因为已经在 Adobe 的 GitHub 询问 ( https://github.com/adobe-fonts/source-han-sans/issues/297 )，获得的回答是之后才会发布步骤，因此才想要询问看看您有没有相关资源。

P/S: 您可以在 commit txt 文件后关闭此 issue.

**Comment by NightFurySL2001** [comment]
借问下，部分字型看起来并没有太大地区差异，请问为什么会重绘呢？有什么考量因素吗？
![image](https://user-images.githubusercontent.com/33471049/129466678-543354d1-7b25-4666-8d49-b62457f3e419.png)

**Comment by NightFurySL2001** [comment]
熳 (U+71B3) 似乎可以直接映射至思源的 uni71B3uE0101-JP (CID: /62498)，无需修改。

**Comment by NightFurySL2001** [comment]
籍 (U+7C4D) 似乎可以直接映射至思源的 uni7C4DuE0101-JP (CID: /62593)，无需修改。Chiron 可能需要检查下异选字所提供的字形是否可以直接使用。
![image](https://user-images.githubusercontent.com/33471049/130353573-44e3f957-ba56-4628-9712-228828e95522.png)

**Comment by tamcy** [comment]
對於為甚麼那些看來符合本字體要求的字會重繪，最「官方」的解釋是「個人需要」。

這不是說昭源是一個完全隨心的成品。例如你問及「嘢嗌」一類字，重繪的實際原因是：[思源 CN/TW/HK 源的「口」旁的對齊不佳](https://github.com/adobe-fonts/source-han-sans/issues/99#issuecomment-150889883)，這在粵語當不少「口」部字連用時（例如「嗰啲嘢嘅」）會非常明顯，而**我在使用時遇到了這個問題**，所以所以重繪了部份「口」部字。

說「官方」解釋是「個人需要」的原因是，自問沒有能力處理其他人類似的重繪改善要求（若以「字形佈局不佳」為解釋，我肯定之後會遇到「既然是這個原因，那麼這些字也應該要重繪」一類 issue report），這原則上是屬於上游思源黑體的責任。而我現實中有其他麻煩事纏身，實在沒法詳細一一交代某字重繪的實際原因。這一點請大家體諒。我會建議有疑問時，將昭源和思源的字形比較一下，相信不難知道答案。

另外，謝謝有關可重用 CID 的回報。其實這是因為昭源在作業上只支援在 CMap 表同一字碼各地區的預設字形內做 remap，所以須以 IVS 調出的非地區預設字形會被忽略。換言之，這屬於技術問題（最近才加上支援 remap 到同一字碼下的 IVS，#10 的「U+74CA 瓊」是第一個 remap 到 IVS CID 的字碼，但在作業流程上也不算十分方便）。我做過檢查，閣下提出的熳、籍和另外一兩個字碼在下一版會用回思源字圖，但有些我認為重繪版效果較佳故保留。其實，這類不同 CID 字形相同的情況在思源也有（雖然原因不同），若不是字形有問題建議不必在這方面費神（昭源沒有 CID 不夠用的隱憂）。開發格言有云：If It Ain't Broke, Don't Fix It.

**Comment by tamcy** [comment]
已將 upstream_differences.txt 加到 repo。

Pro 版因嵌入 Source Sans 3，情況較複雜，暫未能提供此檔。

**Comment by NightFurySL2001** [comment]
感谢！

**Comment by NightFurySL2001** [comment]
P/S: `CHANGELOG.md` 可能可以在2.044版本提及upstream_differences的存在，更新2.041版本的以下句子：
> All daily used characters should now adhere to the font's preferred form. Starting from v2.040, redesigned characters that are not frequently used will not be explicitly mentioned in the changelog (this file). Please consult meta.json for the redesigned character count of each release.
