### ISSUE TITLE
未改全字符

### ISSUE THREAD

**Issue by NightFurySL2001** [chiron-fonts/chiron-sans-hk#22]
![image](https://user-images.githubusercontent.com/33471049/129477561-a5355436-44cc-4227-af89-20266f14d1d7.png)

**Comment by NightFurySL2001** [comment]
另，如果“缶”选择两边齐脚，为什么“缺”会选择重绘左边没脚的版本呢？
![image](https://user-images.githubusercontent.com/33471049/130353992-61eaa657-bd74-4404-94b7-1b6382c37599.png)

**Comment by NightFurySL2001** [comment]
炎的下面火有些没有切平人形。
![image](https://user-images.githubusercontent.com/33471049/130358712-c689432f-7624-4f0d-b1c4-25a78553522f.png)

**Comment by tamcy** [comment]
### 「悐」字形問題

有關「捺變作點」的問題，我在[這裏](https://github.com/chiron-fonts/chiron-sans-hk/issues/16#issuecomment-818772260)已有做過說明。簡言之，這種「從點從捺」並非我執着的範圍，尤其在「捺點差異不在字底、思源不會將點筆跟其他筆畫斷開」的情況。

「悐」字本來是用思源 V1 日本字圖，該字形正是從捺。後來因為 VF 版出現而必須人手重繪幾十個這類字圖。那時沒有再在火字部下工夫，大抵是「狄」在上方只此一字而「悐」字罕用使致。當然，假如單純以「火」部件為單位， 以「愁」做參考，「狄」尾筆是改做撇較合適，但此字罕用，似無急切需要（有類似情況的其實不止這一字，何況我也說過，一般人閱讀時根本不會在意這種事）。

### 「火」字的「人」部件設計

為減少重繪字符量、增加 remapping 彈性，昭源本來就「放寬」了一些本來在思源屬地區差異的設計，例如「𠂆」「了」是否做成一筆過之類。至於火字的「人」部件設計，連思源也不是涇渭分明，像「啖」字的 CN 版就用了 JP 源的字形，而 JP/KR 源的字圖也有一些人部件跟 CN 版相近只是撇筆非常高，亦即其實粗略估計在思源火部件的人字共有三種設計。這類字並無給我觀感上的不同，所以也視為「可忽略差異」。若是指昭源重繪時的不一致，有可能是改的時候（尤其開發初期）對這個部件還沒有一個很強烈的傾向，所以哪個方便、合用就選哪一個。既然我接受這種在源檔的不一致，之後也就沒有再逐一審核重繪字形去再改成最後屬意的樣式。

由於兩個都不屬 bug，我會標籤為 as designed 然後關閉。「悐」日後或會在理順類近情況時修改，「炎」系字修改機會微。
