### ISSUE TITLE
橫排和直書 palt/vpal 特性移除情況不一

### ISSUE THREAD

**Issue by toto-minai** [chiron-fonts/chiron-sans-hk#24]
橫排和直書移除了 `「『』」` 的 `palt`/`vpal`，而直書似乎保留了 `《》（）`，但在橫排，僅保留了 `（）`。請問這是設計上的考慮嗎？

**Comment by tamcy** [comment]
是 Bug，之前忽略了。會在下一版修正，謝謝回報！

**Comment by tamcy** [comment]
Fixed in v2.046.
