### ISSUE TITLE
關於介紹文本的建議

### ISSUE THREAD

**Issue by Guest-615695028** [chiron-fonts/chiron-sans-hk#25]
> 有些筆畫本來不屬「標準差異」，但思源黑體因為各種原因以「地區差異」將寫法區分。昭源黑體會盡量選擇設計較佳的版本，不拘泥於原來字體對該種筆畫的地區劃分。
> 大多數筆畫的相連與否其實不屬標準差異。「無」字上方和「⺮（竹花頭）」部件，昭源黑體決定選用「**中**日韓」版本的上下相連版本，因為這比「港台」版的做法可以減低視覺辨認上的混亂。
> 「金、食」等「人」部件在頂部的字，思源黑體對「人」字兩筆起筆是否黏連視為「日韓」版和「**中**港台」的地區差異（日韓版黏連，**中**港台版則否）。但事實上黏連寫法起碼在港台標準並無問題。昭源黑體選用整體設計明顯較佳的「日韓」版字形（試比較圖例中「鏜」字兩個版本的佈局差異）。
> 雖然不屬標準差異，為保持排版時字形一致，昭源黑體仍會按選定式樣重繪相同部件的字，例如圖中「鈽」字就是昭源黑體重繪版本。
> 因着「人」部件的選擇，昭源黑體設計了本來思源黑體沒有的「日版亼」加「港版艮」的「食」字部件。
加粗「中」字均改爲「陸」字，以免獲指控爲「台獨」「港獨」。

**Comment by tamcy** [comment]
本網頁已經清楚寫明描述的是「地區差異」，即如 https://github.com/adobe-fonts/source-han-serif/issues/78 一樣。欲加之罪何患無辭，要上綱上線即使按閣下要求更改也一樣可以有人不滿。

昭源黑體網頁寫明以「新字形」為基礎，閣下就[拿出「舊字形」文件要求我修改](https://github.com/chiron-fonts/chiron-sans-hk-pro/issues/4)；我在網頁寫明以 Big5+HKSCS 中的常用字為重點，而你就開 issue 要我覆蓋 URO 和 Ext-A；我寫過支援範圍在 Big5+HKSCS，[你就搬出另一套標準通用規範漢字表再抽出列出非 BMP 的一大串字符問我會如何處理](https://github.com/chiron-fonts/chiron-sans-hk-pro/issues/3)。種種態度令我覺得你根本完全沒有看過本專案任何説明文件，只是按一己之意行事。但從此一 issue 看來，其實閣下並非沒有注意到本專案網頁，只是對網頁中有關本字體的種種製作背景、説明、支援範圍等等內容視若無睹，而是無端白事將網頁內容泛政治化。

幾此一 issue 和之前 二事，加上閣下在 Adobe 的思源黑體Github 網站也充份表現出[閣下提出 issue 前完全不做功課（例如搜尋舊 issue 看看是否已有人提出類似問題）](https://github.com/adobe-fonts/source-han-sans/issues/305)（當然現在看來也許是明知而故犯）、在[另一 issue 又將字體美觀與否與「辱華」扯上關係](https://github.com/adobe-fonts/source-han-sans/issues/325)（事實上大部份中國版字形是來自常州華文）兼犯上基本事實錯誤（例如將蘋方稱為思源黑體的父字體，事實上二者毫無關連，而且思源黑體先推出於蘋方），加上閣下在自己 Github 上傳版權字體等種種行徑，實令我無法認為本人所作昭源各字體能滿足閣下要求。既然如此，勸閣下不必浪費時間，勞煩將提出意見、批評等諸般心力，移師他處，則雙方幸甚。
